version: '3'

services:
  blog_api:
    container_name: strapi
    image: wahnsinnshub/blog.andkra.eu.backend
    env_file:
      - strapi.env
    environment:
      - VIRTUAL_HOST=api.andreaskrahl.local
      - VIRTUAL_PORT=1337
      - LETSENCRYPT_HOST=api.andreaskrahl.local
      - LETSENCRYPT_EMAIL=andi@radikrahl.com
    depends_on:
      - db
    networks:
        - frontproxy_default
        - default
  blog_app:
    container_name: web
    image: wahnsinnshub/blog.andkra.eu.frontend
    environment: 
      - VIRTUAL_HOST=app.andreaskrahl.local
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=app.andreaskrahl.local
      - LETSENCRYPT_EMAIL=andi@radikrahl.com
    networks:
      - frontproxy_default
      - default
  db:
    container_name: mysql
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - db.env
    volumes:
      - ./strapi/db:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - "3306"
    networks:
      - frontproxy_default
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
networks:
    frontproxy_default:
      external: true