version: '3.3'

networks:
  db_backend:
  traefik_webgateway:
    external: true

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - db_backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wpblog.rule=Host(`${DOMAIN_WPBLOG}`)"
      - "traefik.http.routers.wpblog.entrypoints=websecure"
      - "traefik.http.routers.wpblog.tls.certresolver=myresolver"
      - "traefik.http.routers.wpblog.tls=true"
      - "traefik.http.services.wpblog.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_webgateway"
    networks:
      - traefik_webgateway
      - db_backend
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_WEBSITE_URL: ${WORDPRESS_WEBSITE_URL}
volumes:
    db_data: {}