version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    user: root
    networks:
      - frontproxy_default
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker:ro
    environment:
      - VIRTUAL_HOST=jenkins.andreaskrahl.local
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.andreaskrahl.local
      - LETSENCRYPT_EMAIL=andi@radikrahl.com
volumes:
  jenkins_home:
networks:
  frontproxy_default:
    external: true
