version: '3'
services:
  default.vhost:
    # image: ghost
    container_name: default.vhost
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    networks:
        - frontproxy_default
        - default
    environment:
      - VIRTUAL_HOST=andreaskrahl.local.de
      - LETSENCRYPT_HOST=andreaskrahl.local
      - LETSENCRYPT_EMAIL=andi@radikrahl.com
networks:
    frontproxy_default:
      external: true