version: '3.7'

networks:
  traefik_webgateway:
    external: true

services:
  ghost:
    # https://hub.docker.com/_/ghost/
    image: ghost:3-alpine
    restart: unless-stopped
    networks:
      - traefik_webgateway
    volumes:
      - ./content:/var/lib/ghost/content
      # - /configuration
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`${DOMAIN_BLOG}`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls.certresolver=myresolver"
      - "traefik.http.routers.ghost.tls=true"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"